reporting.reporting_endpoint.*:
  type: config_entity
  label: 'Reporting Endpoint config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

csp_reporting_handler.reporting:
  type: mapping
  label: 'Reporting Endpoint'
  mapping:
    endpoint:
      type: string
      label: 'Endpoint ID'
